services:
  backend:
    build:
      context: ./backend
    container_name: birth-backend
    ports:
      - "3001:3001"
    volumes:
      - ./database:/app/database
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://backend:3001
    container_name: birth-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: birth-certificate-network

volumes: {}